export type Bill = {
  id: number;
  description: string;
  due_day: number;
  payment_method: string;
  country: string;
  base_value: number;
  jan_value: number | null;
  feb_value: number | null;
  mar_value: number | null;
  apr_value: number | null;
  may_value: number | null;
  jun_value: number | null;
  jul_value: number | null;
  aug_value: number | null;
  sep_value: number | null;
  oct_value: number | null;
  nov_value: number | null;
  dec_value: number | null;
  jan_status: boolean;
  feb_status: boolean;
  mar_status: boolean;
  apr_status: boolean;
  may_status: boolean;
  jun_status: boolean;
  jul_status: boolean;
  aug_status: boolean;
  sep_status: boolean;
  oct_status: boolean;
  nov_status: boolean;
  dec_status: boolean;
  current_month_status: boolean;
  current_month_value: number | null;
  created_at: string;
  updated_at: string;
}; 